##Each new term in the Fibonacci sequence is generated by adding the previous
##two terms. By starting with 1 and 2, the first 10 terms will be:
##
##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
##By considering the terms in the Fibonacci sequence whose values do not
##exceed four million, find the sum of the even-valued terms.

from time import time
import sys
sys.path.append("../Library")
from peresult import peresult

def solve():
    start = time()
    twoago = 1
    oneago = 2
    thisterm = 0
    result = 2
    while thisterm < 4000000:
        thisterm = twoago + oneago
        if thisterm % 2 == 0:
            result += thisterm
        twoago, oneago = oneago, thisterm
    peresult(2, result, time() - start)

if __name__ == "__main__":
    solve()
