##Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2.
##The first ten pentagonal numbers are:
##
##1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
##
##It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their
##difference, 70 − 22 = 48, is not pentagonal.
##
##Find the pair of pentagonal numbers, Pj and Pk, for which their
##sum and difference are pentagonal and D = |Pk − Pj| is minimised;
##what is the value of D?

from time import time
import sys
sys.path.append("../Library")
from peresult import peresult
from math import sqrt

def solve():
        start = time()
        pentanums = [1, 5]
        pentacreator = 3
        while True:
                pentanums.append(pentacreator * (3 * pentacreator - 1) // 2)
                pentacreator += 1
                for index in range(len(pentanums) - 2, -1, -1):
                        if ispenta(pentanums[-1] + pentanums[index]):
                                if ispenta(pentanums[-1] - pentanums[index]):
                                        result = pentanums[-1] - pentanums[index]
                                        break
                else:
                        continue
                break
        peresult(44, result, time() - start)

def ispenta(num):
        if (1 + sqrt(1 + 24 * num)) / 6 % 1 == 0:
                return True
        return False

if __name__ == "__main__":
        solve()
