# Triangle, pentagonal, and hexagonal numbers are generated by the
# following formulae:
# 
# Triangle	Tn=n(n+1)/2	1, 3, 6, 10, 15, ...
# Pentagonal	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
# Hexagonal	Hn=n(2n−1)	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# 
# Find the next triangle number that is also pentagonal and hexagonal.

from time import time
import sys
sys.path.append("../Library")
from peresult import peresult
from pe44PentagonNumbers import ispenta #I think I'm allowed to do this

def solve():
        start = time()
        n = 144
        while not ispenta(n * (2 * n - 1)):
                n += 1
        peresult(45, n * (2 * n - 1), time() - start)

if __name__ == "__main__":
        solve()
